name: Build Tamara Webapp

on:
  push:
    branches: [ master ]

env:
  repository: tamara/webapp
  role_arn: arn:aws:iam::916148231619:role/fiter-us-east-2-dev-ghdeploy-role-tamara
  region: us-east-2

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
        with:
          fetch-depth: 0

      - name: Get the short commit message
        id: short-commit-message
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.role_arn }}
          role-session-name: ecr_deploy
          aws-region: ${{ env.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.repository }}
          COMMIT_HASH: ${{ steps.short-commit-message.outputs.commit_hash }}
          
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$COMMIT_HASH
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$COMMIT_HASH

      - name: Print image tags
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.repository }}
          COMMIT_HASH: ${{ steps.short-commit-message.outputs.commit_hash }}
        run: echo "The image has been pushed to $ECR_REGISTRY/$ECR_REPOSITORY:latest and $ECR_REGISTRY/$ECR_REPOSITORY:$COMMIT_HASH"